# SPDX-FileCopyrightText: Copyright (c) 2019-2026 Aibolit
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/python
assets:
  twine_token: yegor256/cqfn-secrets#twine_token
architect:
  - yegor256
install: |
  curl -LsSf https://astral.sh/uv/0.7.13/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
  uv tool install twine
merge:
  script: |
    make
release:
  script: |-
    sed -i "s/0\.0\.0/${tag}/g" aibolit/__init__.py
    git add aibolit/__init__.py
    git commit -am "${tag}"
    uv run python --version
    uv --version
    make
    make e2e
    uv run twine upload dist/* -u __token__ -p $(cat ../twine_token)
