FROM python

RUN git config --global user.email "docker@example.com"
RUN git config --global user.name "Docker Dockerovich"

# fetch and install Aibolit from source#
ADD ./git_clone_and_pull_pr.sh .
RUN chmod +x ./git_clone_and_pull_pr.sh
RUN ./git_clone_and_pull_pr.sh

RUN mkdir in
RUN mkdir out

ENTRYPOINT []
CMD ["aibolit", "recommend",  "--folder=./in",  "--output=./out/out.xml"]