# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Aibolit
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.11
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
      - run: gem install xcop
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/0.7.13/install.sh | sh
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - run: make
