# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Aibolit
# SPDX-License-Identifier: MIT
---
name: Pyright
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Pyright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Static Analysis
        run: uvx pyright --level error
