# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Aibolit
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: style
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - run: make style
