# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Aibolit
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: up
'on':
  push:
    branches:
      - master
    tags:
      - '*'
concurrency:
  group: up-${{ github.ref }}
  cancel-in-progress: true
jobs:
  up:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: |-
          git fetch --tags --force && \
          latest=$(git tag --sort=creatordate | tail -1) && \
          sed -E -i "s|aibolit=[^ ]+|aibolit==${latest}|g" README.md
      - uses: peter-evans/create-pull-request@v7
        with:
          sign-commits: true
          branch: version-up
          commit-message: 'New version in README'
          delete-branch: true
          title: 'New version in README'
          assignees: yegor256
          base: master
